export enum ColumnsEnum {
  id = 'id',
  name = 'name',
  surname = 'surname',
  email = 'email',
  phone = 'phone',
  age = 'age',
  course = 'course',
  course_format = 'course_format',
  course_type = 'course_type',
  status = 'status',
  sum = 'sum',
  alreadyPaid = 'alredyPaid',
  group = 'group',
  created_at = 'created_at',
  manager = 'manager',
}
